version: '3'
services:
    jekyll:
        image: jekyll/jekyll:pages
        container_name: takacsmark-dot-com
        command: bundle exec jekyll serve --host 0.0.0.0 --drafts --config _config.yml,_config_dev.yml --watch --incremental
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
    node-automation:
        build: .
        image: takacsmark/node-automation:jekyll
        container_name: node-automation
        command: /bin/sh
        stdin_open: true
        tty: true
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
